### PR TITLE
Create header file for common benchmark functions

### PR DESCRIPTION
**Pull request by andreaskurth**
This is not fully finished, I will update the existing apps to use the `bench_` functions and test them.  Nonetheless, I would like to get your feedback at this point.

There are two changes in this PR:

First, I created the `common/bench.h` file, which contains implementations of two functions commonly used in benchmarks: `bench_start()` and `bench_stop()`.  Please have a look at API and implementation and let me know what you think.

Second, application binaries are no longer named `app.exe` by default because `app` is too generic, resulting in overwrites during deployment, and `.exe` is very unusual on Linux systems. Instead, the name of the folder in which the Makefile is placed is inherited, which leads to very "natural" automatic names. The only drawback I see is that a wildcard `*.exe` git-ignore no longer works, so we have to create one `.gitignore` file per app (I already did so for the existing apps.)

### CODE REVIEW

**Review by alessandrocapotondi — APPROVED** [review]

**Review by alessandrocapotondi — APPROVED** [review]

**Comment by alessandrocapotondi** [comment]
I like the modifications. @accuminium do you need to add some more commits or I can merge as it?

**Comment by andreaskurth** [comment]
Thanks, Alessandro.  I found some corner cases in tests and am currently ironing them out, so it's still WIP. Also, let's wait for Pirmin's feedback.

**Review by vogelpi — APPROVED** [review]
I did not check in detail the implementation of the timing functions. But I think it all makes sense and is useful.

**Comment by andreaskurth** [comment]
Found and fixed the overflow problem. Tests on `mm-versions` pass. Thanks for your reviews, I merge it now.

**Pull request merged**
