### PR TITLE
Release v1.0.1

### PR DESCRIPTION
**Pull request by andreaskurth**
Patch release to fix the following:
1. Add license header to all C files.
2. Ensure that remote directory exists during `make install`.
3. `common/bench.h:` Add missing include guard.

I am currently testing points 2 and 3 but they are minor, so I do not expect major problems.

About point 1, @alessandrocapotondi please check the license headers for files in the [sobel](https://github.com/pulp-platform/hero-openmp-examples/tree/rel-v1.0.1/sobel) directory. I added custom headers there because the files are copied from a GitHub repo that does not have a license on it. This looks like sufficient attribution and fair reuse to me, but I am not a lawyer and would like your approval as the one who imported the code.

Anything else requiring a patch right now?

## WIP Items
- [x] Test if `helloworld` runs in parallel
- [x] Compile and run the other apps, check run time.
- [x] Assert target directory creation incl. already existing.

### CODE REVIEW

**Comment by vogelpi** [comment]
Thanks @accuminium . This sounds reasonable to me.

**Comment by vogelpi** [comment]
Could you please also check the `helloworld` app again. I just noted that on my setup (not updated to the latest versions) the host just does a single print, meaning it is not parallelized.

**Review by vogelpi — COMMENTED** [review]
Okay, thank you.

**Comment by alessandrocapotondi** [comment]
@vogelpi @accuminium, I will check the last build version  and I will let you know.

About the sobel application we can also for the moment remove such application and then I will ask the owner to add a license.

For me is the same.

**Comment by alessandrocapotondi** [comment]
On my setup I don't see any issues with the `helloworld`:

```
Hello World, I am thread 3 of 8
Hello World, I am thread 4 of 8
Hello World, I am thread 5 of 8
Hello World, I am thread 7 of 8
Hello World, I am thread 6 of 8
Hello World, I am thread 0 of 8
Hello World, I am thread 1 of 8
Hello Wo
```

**Comment by alessandrocapotondi** [comment]
@accuminium, @vogelpi,

I created a PR to the owner of the code to add a license apache v2
https://github.com/petermlm/SobelFilter/pull/1

Let's see what happens. If it is the last point for the release I can remove right now the application and in case I can add it later.

Alessandro

**Comment by andreaskurth** [comment]
I removed the code for the app, so we are on the safe side.  We can add it back later.

**Comment by andreaskurth** [comment]
Thanks for your feedback, I will merge this and release v1.0.1.

**Pull request merged**
